### ISSUE TITLE
Will `impl Send for spsc::Producer` and `load(Ordering::Relaxed) in Queue::inner_enqueue` lead to unexpected behaviours?

### ISSUE THREAD

**Issue by shadw3002** [rust-embedded/heapless#343]
Hi, I am a beginner in the field of concurrent programming, during learning I found this package and try to learn how to implement a SPSC Quene, but I am confuse about [the Send trait of spsc::Producer](https://docs.rs/heapless/latest/src/heapless/spsc.rs.html#498) and [the Ordering::Relaxed in spsc::Queue::inner_enqueue](https://docs.rs/heapless/latest/src/heapless/spsc.rs.html#216). 

Situation:

| ts | thread A                            | thread B                      |
| -- | -- | -- |
|  0 |  create producer p        |                                         |
|  1 | p.enqueue(...)                 |                                         |
|  2 | move p to thread B       |  p                                     |
|  3 |                                               |  p.enqueue(...)           |
|  4 |                                               | move p to thread A  |
|  5 | p.enqueue(...)                 |                                          |

Question:
Assume tail starts with 0, at ts 3,  p.enqueue(...) write tail with `store(2, Ordering::Release)`, at ts 5, will p.enqueue(...) see tail is 1 with `load(Ordering::Relaxed)` ? 

At last, thanks for reading my issue, maybe it's my misunderstanding leads to my confusion.

**Comment by reitermarkus** [comment]
Since only a single thread can ever `enqueue` at the same time, due to `Queue` being `!Sync`, `Ordering::Relaxed` in `spsc::Queue::inner_enqueue` is enough.

In your example, in order to even “move p” to another thread, some kind of synchronisation has to occur, ensuring correct ordering.
