### ISSUE TITLE
Implement `serde::Serialize` and `serde::Deserialize` for `heapless::Deque`

### ISSUE THREAD

**Issue by wiktorwieclaw** [rust-embedded/heapless#367]
* [`serde` implements `serde::Serialize` for `std::collections::VecDeque`](https://github.com/serde-rs/serde/blob/a0f850f15bd5beb406d9b899e0f5dc9b7b01641f/serde/src/ser/impls.rs#L238)
* [`heapless` already implements serde::Serialize for `heapless::Vec`](https://github.com/japaric/heapless/blob/644653bf3b831c6bb4963be2de24804acf5e5001/src/ser.rs#L44-L58).

Same thing applies to `serde::Deserialize`. I don't see any reason to leave `Deque` out.

**Comment by Dirbaio** [comment]
done in #370
