### ISSUE TITLE
Would it be possible to create a new release?

### ISSUE THREAD

**Issue by JelteF** [rust-embedded/heapless#373]
I'm looking forward to using this this change so I can simply use `#[derive(Hash)]`: https://github.com/japaric/heapless/pull/284

**Comment by elpiel** [comment]
Yes, please! I'm also looking for this new release because of hash32 using the core `Hash` and support from enums.

**Comment by JelteF** [comment]
Even a beta release would be very helpful

**Comment by newAM** [comment]
The crate was recently transferred to the newly created libs team: <https://github.com/rust-embedded/wg/issues/710>

We are actively working on a new release, just trying to close off as many outstanding issues as possible (especially ones that require breaking changes).
