### ISSUE TITLE
Swap atomic-polyfill for portable-atomic

### ISSUE THREAD

**Issue by thejpster** [rust-embedded/heapless#374]
https://crates.io/crates/atomic-polyfill says:

> ⚠️ THIS CRATE IS DEPRECATED ⚠️
>
> Use [portable-atomic](https://crates.io/crates/portable-atomic) instead. It supports many more architectures and more efficient ways of emulating atomics.

**Comment by thejpster** [comment]
Oh, there's a PR in #328

**Comment by newAM** [comment]
Fixed in #328 :tada:
