### ISSUE TITLE
Implement `TryFrom<&str>` for fallible conversion

### ISSUE THREAD

**Issue by faern** [rust-embedded/heapless#381]
It's currently a bit cumbersome to go from a regular Rust string to a `heapless::String` and properly catch if it does not fit. The current `From<&str>` impl panics if the string is too long. It would be nice with a corresponding `TryFrom` impl.

The current best way is to create an empty heapless string and use `push_str` and catch the error there. But it's not very ergonomic.

**Comment by newAM** [comment]
Fixed in #397
