### ISSUE TITLE
Add TwoSidedVec

### ISSUE THREAD

**Issue by Rosdf** [rust-embedded/heapless#406]
In one of my projects i need two sided vector (like this one https://docs.rs/two-sided-vec/latest/two_sided_vec/), but with static capacity. Thought that this library would be perfect place for it. I'm ready to take it one me and make PR.

**Comment by reitermarkus** [comment]
Is this the same thing as [`std::collections::VecDeque`](https://doc.rust-lang.org/std/collections/struct.VecDeque.html)?

**Comment by reitermarkus** [comment]
Closing due to no response.
