### ISSUE TITLE
Backport xtensa atomic detection to a 0.7.x release

### ISSUE THREAD

**Issue by MabezDev** [rust-embedded/heapless#422]
If we backport https://github.com/rust-embedded/heapless/commit/02935035b12bedea380caa245d6d3f6d815ee3b5 to a 0.7.x patch release, we can avoid breakage as crates slowly migrate to 0.8. 

Discussion [here](https://matrix.to/#/!YoLPkieCYHGzdjUhOK:matrix.org/$dV2c98J8RkjBHsLyiYNZJomku-vd3cDkeE2cEy-b_pE?via=matrix.org&via=grusbv.com&via=tchncs.de)

**Comment by Dirbaio** [comment]
done in #423
