### ISSUE TITLE
Add a cheap `HistoryBuffer::empty` method

### ISSUE THREAD

**Issue by Eugeny** [rust-embedded/heapless#432]
Currently there's no easy way to drain a `HistoryBuffer` without zeroing it.

A simple function like this would come in handy in performance critical situations:

```rust
fn empty(&mut self) {
  self.write_at = 0;
  self.filled = false;
}
```

**Comment by Dirbaio** [comment]
@Eugeny could you share a snippet of code where `clear()` is causing slow zeroing of the buffer, and your proposed `empty()` doesn't, *when building with optimizations*?

**Comment by reitermarkus** [comment]
Closing due to no response and `clear` already producing the same code.
