### ISSUE TITLE
doc examples errors

### ISSUE THREAD

**Issue by jordens** [rust-embedded/heapless#440]
e.g. 

https://github.com/rust-embedded/heapless/blob/cbd406eab8eaba37206cd9f4924b1e4bdf314d5d/src/vec.rs#L19C1-L20C1

`push()` is fallible. The `Result` should be used, even if it is just `.ok()`ed.

**Comment by newAM** [comment]
Do you know of an automated way to check for this?  I can fix that specific example, but there are probably more in the codebase.

**Comment by jordens** [comment]
Not aware of anything other than what you already found: https://github.com/rust-embedded/heapless/pull/416#issuecomment-1816861426

**Comment by jordens** [comment]
#441
